services:
  postgres:
    image: postgres:15
    container_name: postgres-springboo
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: